#!/bin/bash

function usage() {
    local us=(
        "Flages:"
        "   verx -h: help"
        "   verx -d: about verx"
        "   verx -v: verx version"
        "Usage:"
        "   Latest version:"
        "       verx OWNER/REPO_NAME -l"
        "   Current version:"
        "    inside repo folder"
        "       verx -c"
    )
}

latest() {
    if [ -x '$(command -v curl)' ]; then
        curl --silent "https://api.github.com/repos/$1/releases/latest" | # Get latest release from GitHub api
            grep '"tag_name":' |                                          # Get tag_name line
            sed -E 's/.*"([^"]+)".*/\1/'                                  # Pluck JSON value
    fi
}

current() {
    if [ -x "$(command -v git)" ]; then
        git describe --abbrev=0 --tags
    fi
}

while (($#)); do
    case "$1" in

    --help | -h)
        usage
        exit 0
        ;;

    --version | -v)
        verx abdfnx/verx -c
        exit 0
        ;;

    -d)
        verx abdfnx/verx -c
        exit 0
        ;;

    -c)
        current
        exit 0
        ;;

    esac

    case "$2" in

    -l)
        latest $1
        exit 0
        ;;

    esac
done
